# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  toolchain.directory: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin
  bin.directory: C:/Library/Swift-development/bin
  icu.directory: C:/Library/icu-67/usr/bin

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: specific
    project: '3133d6ab-80a8-4996-ac4f-03df25cd3224'
    allowPartiallySucceededBuilds: true
    pipeline: 1
    artifactName: 'zlib-${{ parameters.platform }}-${{ parameters.host }}'
    downloadPath: '$(System.ArtifactsDirectory)'
  displayName: Download zlib

- task: BatchScript@1
  displayName: VsDevCmd
  inputs:
    filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
    arguments: -no_logo -arch=x64 -host_arch=x64
    modifyEnvironment: true

- script: |
    curl -L "https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Platform/ucrt.modulemap" -o "%UniversalCRTSdkDir%\Include\%UCRTVersion%\ucrt\module.modulemap"
    curl -L "https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Platform/visualc.modulemap" -o "%VCToolsInstallDir%\include\module.modulemap"
    curl -L "https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Platform/visualc.apinotes" -o "%VCToolsInstallDir%\include\visualc.apinotes"
    curl -L "https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Platform/winsdk.modulemap" -o "%UniversalCRTSdkDir%\Include\%UCRTVersion%\um\module.modulemap"
  displayName: Configure SDK

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Binary -Url "https://swift.org/builds/development/windows10/swift-DEVELOPMENT-SNAPSHOT-03-21-a/swift-DEVELOPMENT-SNAPSHOT-03-21-a-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
      Write-Host "##vso[task.prependpath]$(toolchain.directory)"
      Write-Host "##vso[task.prependpath]$(bin.directory)"
      Write-Host "##vso[task.prependpath]$(icu.directory)"
  displayName: Install toolchain

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Expand-Archive -Force '$(System.DefaultWorkingDirectory)/Zlib.zip' 'C:/Library'
  displayName: Install Zlib

- script: |
    swift build -v -c release
  env:
    SDKROOT: C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk
    DEVELOPER_DIR: C:\Library\Developer
  displayName: 'Build swift package'
