name: Windows

on:
  push:
    branches: [windows]
    
jobs:
  windows:
    runs-on: windows-latest
    steps:

      - name: vcpkg install libxlsxwriter
        run: |
          vcpkg install libxlsxwriter:x64-windows
          vcpkg integrate install
        continue-on-error: true

      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.5.2-release
          tag: 5.5.2-RELEASE

      - uses: actions/checkout@v2
        with:
          ref: vcpkg

      - name: Build swift .dll in release mode
        run: swift build -c release -Xswiftc -LC:/vcpkg/installed/x64-windows/lib/
        continue-on-error: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: xlsxwriter-win32-x64
          path: .build\x86_64-unknown-windows-msvc\release\*.dll

